import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { ReactNode } from "react";
import { Providers } from "@/components/providers";
import "@/app/globals.css";
import { CartProvider } from "../context/CartContext";
import NotificationProvider from "@/components/NotificationProvider";
import OrderConfirmProvider from "@/components/OrderConfirmProvider";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['500'],
  variable: '--font-plus-jakarta-sans',
})

export const metadata: Metadata = {
  title: "Panganku Fresh",
  description: "Generated by create next app",
  icons: {
    icon: "/panganku-fresh-icon.png",
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={plusJakartaSans.variable}>
      <body>
        <Providers>
  <NotificationProvider>
    <CartProvider>
      <OrderConfirmProvider>
        {children}
      </OrderConfirmProvider>
    </CartProvider>
  </NotificationProvider>
</Providers>
      </body>
    </html >
  );
}