import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from 'next/font/google'
import "./globals.css";
import { ReactNode } from "react";
import Navbar from "@/components/Navbar";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['300'],
  variable: '--font-plus-jakarta-sans',
})

export const metadata: Metadata = {
  title: "Regar Mart App",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png',
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={plusJakartaSans.variable}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
