import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['500'],
  variable: '--font-plus-jakarta-sans',
})

export const metadata: Metadata = {
  title: "Regar Mart", 
  description: "Generated by create next app",
  icons: {
    icon: "/Logo.png",
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={plusJakartaSans.variable}>
      <body>
          {children}
      </body>
    </html>
  );
}