import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from 'next/font/google'
import { ReactNode } from "react";
import Sidebar from "./components/Sidebar";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['500'],
  variable: '--font-plus-jakarta-sans',
})

export const metadata: Metadata = {
  title: "Regar Mart Admin",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png',
  },
};

interface AdminLayoutProps {
  children: ReactNode;
}

export default function AdminLayout({ children }: AdminLayoutProps) {
  return (
    <div className="bg-gray-50 flex font-plusJakartaSans min-h-screen">
      <Sidebar title="" subtitle="Admin Dashboard" />
      <main className="flex-1 p-6">
        {children}
      </main>
    </div>
  );
}
